language: python
python:
  - "2.7"
# only test the master branch
branches:
  only:
    - master
# install native libraries
before_install:
 - sudo apt-get install python-dev
 - sudo apt-get install libxml2-dev
 - sudo apt-get install libxslt-dev
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script: python setup.py test